import { useEffect, useState } from 'react';
import Head from 'next/head'
import '../styles/globals.css'

// mui for backgraound
import { Paper } from '@mui/material'

// mui theme
import { ColorContextProvider } from '../theme/MUI_MODE'

// components
import Footer from '../components/module/Footer';
import Navbar from '../components/module/Navbar';
import ScrollToTop from '../components/elements/ScrollToTop'

// redux
import { Provider } from 'react-redux'
import { store } from '../redux/store'

// progressbar
import NextNProgress from "nextjs-progressbar";

function MyApp({ Component, pageProps }) {

  const [hasWindow, setHasWindow] = useState(false);
  useEffect(() => {
    if (typeof window !== "undefined") {
      setHasWindow(true)
    }
  }, []);

  return (
    <>
      <Head>
        <title>ecoShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <ColorContextProvider>
        <Provider store={store}>

          {hasWindow &&
            <Paper variant='elevation'
              sx={{
                boxShadow: 'none', borderRadius: '0',
                border: 'none', p: '0px', m: "0px",
                minHeight: "100vh"
              }}>

              <NextNProgress
                color="#29D"
                startPosition={0.3}
                stopDelayMs={200}
                height={3}
                showOnShallow={true}
              />

              <Navbar />
              <Component {...pageProps} />
              <Footer />
              <ScrollToTop />

            </Paper>
          }


        </Provider>
      </ColorContextProvider>
    </>
  )
}

export default MyApp
